spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:classpath:/local/application-security.yml"

  docker:
    compose:
      enabled: true
      file: /workspaces/codespaces-blank/stomp/docker-compose-local.yml    
      lifecycle-management: start-and-stop

  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/
    
  datasource:
    url: jdbc:mysql://localhost:3306/localdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: localuser
    password: localpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: localuser
    password: localpass
    stomp:
      port: 61613


