spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:classpath:/application-local-security.yml"

  docker:
    compose:
      enabled: true
      file: /workspaces/codespaces-blank/stomp/docker-compose-local.yml
      lifecycle-management: start-and-stop

  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/
    
  datasource:
    url: jdbc:mysql://localhost:3306/localdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: localuser
    password: localpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: localuser
    password: localpass
    stomp:
      port: 61613

jwt:
  secret: v9yBEHMcQfTjWnZr4u7xACFJaNdRgUkXp2s5v8yBEGKbPeShVmYq3tv9yBEHMcQfTjdsakjdsajqqhfhfehfhdsd
  access-token-validity: 3600000        # (60 * 60 * 1000)
  refresh-token-validity: 86400000 # (60 * 60 * 24 * 1000)

